<html>
<body>
    <?php
        echo "
    <table>
        <tr>
            <td>01</td>
            <td>02</td>
            <td>03</td>
        </tr>
        <tr>
            <td>04</td>
            <td>05</td>
            <td>06</td>
        </tr>
        <tr>
            <td>07</td>
            <td>08</td>
            <td>09</td>
        </tr>
        <tr>
            <td>10</td>
            <td>11</td>
            <td>12</td>
        </tr>
        <tr>
            <td>14</td>
            <td>15</td>
            <td>16</td>
        </tr>
    </table>
        "
    ?>
    
</body>
</html>